apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  chart:
    repository: https://itzg.github.io/minecraft-server-charts/
    name: minecraft
    version: 2.0.4
  values:
    # ref: https://hub.docker.com/r/itzg/minecraft-server/
    # ref: https://github.com/helm/charts/blob/master/stable/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: latest

    #podAnnotations:
    #  pre.hook.backup.velero.io/command: '["bash", "-c", "rcon-cli save-off; rcon-cli save-all"]'
    #  post.hook.backup.velero.io/command: '["rcon-cli", "save-on"]'
    #  backup.velero.io/backup-volumes: datadir


    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        memory: 1024Mi
        cpu: 500m

    livenessProbe:
      initialDelaySeconds: 300

    minecraftServer:
      # This must be overridden, since we can't accept this for the user.
      eula: "TRUE"
      # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTB", "SPONGEVANILLA", "CUSTOM"
      type: "VANILLA"
      version: 1.16.1
      # A comma-separated list of player names who should be admins.
      ops: mungrat
      # One of: creative, survival, adventure, spectator
      gameMode: survival
      # Message of the Day
      motd: "Welcome to Logan's automated minecraft server deployment!"
      # Check accounts against Minecraft account service.
      onlineMode: true
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 1024M

      serviceType: LoadBalancer
      loadBalancerIP:


      query:
        # If you enable this, your server will be "published" to Gamespy
        enabled: false
        port: 25565

    ## Additional minecraft container environment variables
    ##
    # extraEnv:
    #   CUSTOM_SERVER:

    persistence:
      ## minecraft data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      dataDir:
        # Set this to false if you don't care to persist state between restarts.
        enabled: true
        Size: 1Gi
