apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.5.8
  values:
    grafana:
      service:
        type: LoadBalancer
      #enabled: false
      ingress:
        enabled: false
        hosts:
        paths:
          - /
      grafana.ini:
        auth.anonymous:
          enabled: true
          org_name: Main Org.
          org_role: Viewer
    prometheus:
      service:
        type: LoadBalancer
      ingress:
        enabled: false
        hosts: test.com
        paths:
          - /

      prometheusSpec:
        additionalScrapeConfigs:
        replicas: 1
        externalLabels:
          cluster: minecraft
       
      server:
        global:
          scrape_timeout: 30s