apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.14.0
  values:
    prometheus:
      service:
        type: loadbalancer
      ingress:
        enabled: true
    grafana:
      ingress:
        enabled: true
